// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Category
{
    [Key]
    [Column("Category_Id")]
    public int CategoryId { get; set; }

    [Column("Category_Name")]
    [StringLength(50)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

}