// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities;

public partial class Order
{
    [Key]
    [Column("Order_Id")]
    public int OrderId { get; set; }

    [Column("Order_Date", TypeName = "date")]
    public DateTime? OrderDate { get; set; }

    [Column("Order_Sum")]
    public double? OrderSum { get; set; }

    [Column("User_Id")]
    public int? UserId { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }
}