// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("Order_Item")]
public partial class OrderItem
{
    [Key]
    [Column("Order_Item_Id")]
    public int OrderItemId { get; set; }

    [Column("Product_Id")]
    public int? ProductId { get; set; }

    [Column("Order_Id")]
    [JsonIgnore]
    public int? OrderId { get; set; }

    public int? Quantity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItems")]
    public virtual Product Product { get; set; }
}