// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    [Column("Product_Id")]
    public int ProductId { get; set; }

    [Column("Product_Name")]
    [StringLength(50)]
    public string ProductName { get; set; }

    public int? Price { get; set; }

    [Column("Category_Id")]
    public int? CategoryId { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [Column("Path_Image")]
    [StringLength(100)]
    public string PathImage { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}