// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft;

namespace Entities;

public partial class User
{
    [Key]
    public int Id { get; set; }

    [Required]
    [Column("User_Name")]
    [StringLength(50)]
    public string UserName { get; set; }

    [Column("First_Name")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("Last_Name")]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}